---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: "Installing packages on CentOS"
      yum:
        name:
          - net-tools
          - which
          - libselinux-python
          - sudo
        state: present
      register: installation_dependencies
      until: installation_dependencies is succeeded
      when:
        - ansible_os_family == 'RedHat'

    - name: "Apt update"
      shell: "apt-get update"
      args:
        warn: False
      register: installation_dependencies
      until: installation_dependencies is succeeded
      when:
        - ansible_os_family != 'RedHat'

    - name: "Installing packages on NON-CentOS"
      apt:
        name:
          - net-tools
          - apt-utils
          - python3-pip
          - sudo
        update_cache: True
        state: present
      register: installation_dependencies
      until: installation_dependencies is succeeded
      when:
        - ansible_os_family != 'RedHat'

    - name: PyMySQL
      pip:
        name: PyMySQL
      register: installation_dependencies
      until: installation_dependencies is succeeded
      when:
        - ansible_distribution == 'Ubuntu'

    - name: "Configure SUDO."
      lineinfile:
        dest: /etc/sudoers
        line: "Defaults    !requiretty"
        state: present

    - name: "Make sure the docs are installed."
      lineinfile:
        dest: /etc/yum.conf
        line: "tsflags=nodocs"
        state: absent
      when:
        - ansible_os_family == 'RedHat'

    - name: "Create group for imaginary host"
      add_host:
        name: imaginary-host
        groups:
          - mysql
          - postgresql
      changed_when: False

  roles:
    - role: geerlingguy.postgresql
      when: inventory_hostname in groups['postgresql']
    - role: geerlingguy.mysql
      when: inventory_hostname in groups['mysql']
