name: "community.zabbix.zabbix_server"
on:
  push:
    paths:
      - 'roles/zabbix_server/**'
      - 'molecule/zabbix_server/**'
      - '.github/workflows/server.yml'
  pull_request:
    paths:
      - 'roles/zabbix_server/**'
      - 'molecule/zabbix_server/**'
      - '.github/workflows/server.yml'
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        molecule_distro:
          #  - container: mysql-centos
          #    image: geerlingguy/docker-centos7-ansible:latest
          #    group: mysql
          #  - container: pgsql-centos
          #    image: geerlingguy/docker-centos7-ansible:latest
          #    group: postgresql
          - container: mysql-ubuntu
            image: solita/ubuntu-systemd:xenial
            group: mysql
            command: /sbin/init
          - container: pgsql-ubuntu
            image: solita/ubuntu-systemd:xenial
            group: postgresql
            command: /sbin/init
          - container: mysql-debian
            image: minimum2scp/systemd-stretch:latest
            group: mysql
          - container: pgsql-debian
            image: minimum2scp/systemd-stretch
            group: postgresql
        collection_role:
          - zabbix_server
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          sudo apt install docker python wget
          python -m pip install --upgrade pip
          pip install -r molecule/requirements.txt

      - name: Download docker-systemctl-replacement
        run: |
          sudo wget https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -O /usr/local/bin/systemctl
          sudo chmod +x /usr/local/bin/systemctl
          sudo PATH=/usr/local/bin:$PATH

      - name: Build the collection
        run: |
          collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
          echo "::set-env name=COLLECTION_FILE::$collection_file"

      - name: Install the collection
        run: ansible-galaxy collection install $COLLECTION_FILE

      - name: Run role tests
        run: >-
          MY_MOLECULE_CONTAINER=${{ matrix.molecule_distro.container }}
          MY_MOLECULE_IMAGE=${{ matrix.molecule_distro.image }}
          MY_MOLECULE_GROUP=${{ matrix.molecule_distro.group }}
          MY_MOLECULE_DOCKER_COMMAND=${{ matrix.molecule_distro.command }}
          molecule test -s ${{ matrix.collection_role }}
